name: openstack-network-agents
summary: OVS provider-bridge helper for OpenStack Network role
description: |
  Provides a helper to configure a provider bridge and OVN physnet mapping.
  This snap is meant to be driven by a subordinate charm and does not ship
  neutron-ovn-metadata-agent.
base: core24
version: "2025.1"
license: Apache-2.0
grade: devel
confinement: strict

package-repositories:
  - type: apt
    cloud: epoxy
    priority: always

platforms:
  amd64:
  arm64:
  s390x:

plugs:
  network-control:
    interface: network-control
  network:
    interface: network
  ovn-chassis:
    interface: content
    target: $SNAP_DATA/microovn/chassis

apps:
  openstack-network-agents:
    environment:
      # Ensure site packages are loaded first
      PYTHONPATH: $SNAP/usr/lib/python3.12:$SNAP/usr/lib/python3.12/site-packages:$SNAP/lib/python3.12:$SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
    command: bin/openstack-network-agents
    plugs:
      - network
      - network-control
      - ovn-chassis

parts:
  openstack-network-agents:
    plugin: python
    source: .
    build-snaps: [astral-uv]
    build-packages:
      - git
      - cargo
      - rustc
    stage-packages:
      - openvswitch-switch
    python-requirements:
      - requirements.txt
    override-build: |
      uv export --frozen --no-hashes --format=requirements-txt -o requirements.txt
      craftctl default
      snap-helpers write-hooks

hooks:
  install:
    plugs: [network, network-control, ovn-chassis]
  configure:
    plugs: [network, network-control, ovn-chassis]
